### ISSUE TITLE
set property with multiple variables

### ISSUE THREAD

**Issue by chielre** [AdeRegt/Xantase#2]
I cannot find a clean way to use text and variables in a set innerHTML method

**My code**
```
set property innerHTML of title to 'title: ' + content.title
```

I did also try
```
set property innerHTML of title to `title: ${content.title}`
```

Is there a way to make this possible?

**Comment by AdeRegt** [comment]
This feature is completed. 
You can use the following: 
`set property of innerHTML of title to 'title: ' & content.title`
